"""
Pre-built training dataset for expense categorization.
500+ examples covering all 13 default categories.
"""

TRAINING_DATA = [
    # Food & Dining (50+ examples)
    ("Starbucks coffee", "Food & Dining"),
    ("McDonald's breakfast", "Food & Dining"),
    ("Chipotle burrito bowl", "Food & Dining"),
    ("Subway sandwich", "Food & Dining"),
    ("Pizza Hut delivery", "Food & Dining"),
    ("Dominos pizza order", "Food & Dining"),
    ("Burger King whopper", "Food & Dining"),
    ("Taco Bell lunch", "Food & Dining"),
    ("Wendy's drive thru", "Food & Dining"),
    ("Chick-fil-A chicken", "Food & Dining"),
    ("Panera Bread soup", "Food & Dining"),
    ("Panda Express", "Food & Dining"),
    ("Five Guys burger", "Food & Dining"),
    ("In-N-Out burger", "Food & Dining"),
    ("Shake Shack", "Food & Dining"),
    ("Dunkin donuts coffee", "Food & Dining"),
    ("Tim Hortons", "Food & Dining"),
    ("Olive Garden dinner", "Food & Dining"),
    ("Applebees restaurant", "Food & Dining"),
    ("Chilis bar grill", "Food & Dining"),
    ("IHOP breakfast", "Food & Dining"),
    ("Denny's diner", "Food & Dining"),
    ("Waffle House", "Food & Dining"),
    ("Red Lobster seafood", "Food & Dining"),
    ("Outback Steakhouse", "Food & Dining"),
    ("Texas Roadhouse steak", "Food & Dining"),
    ("Buffalo Wild Wings", "Food & Dining"),
    ("Wingstop wings", "Food & Dining"),
    ("Popeyes chicken", "Food & Dining"),
    ("KFC fried chicken", "Food & Dining"),
    ("Noodles Company", "Food & Dining"),
    ("Pho restaurant", "Food & Dining"),
    ("Sushi dinner", "Food & Dining"),
    ("Thai food takeout", "Food & Dining"),
    ("Chinese restaurant", "Food & Dining"),
    ("Indian food delivery", "Food & Dining"),
    ("Korean BBQ", "Food & Dining"),
    ("Mexican restaurant", "Food & Dining"),
    ("Italian restaurant", "Food & Dining"),
    ("Steakhouse dinner", "Food & Dining"),
    ("Brunch restaurant", "Food & Dining"),
    ("Coffee shop latte", "Food & Dining"),
    ("Bakery pastry", "Food & Dining"),
    ("Ice cream shop", "Food & Dining"),
    ("Smoothie King", "Food & Dining"),
    ("Jamba Juice", "Food & Dining"),
    ("DoorDash delivery", "Food & Dining"),
    ("UberEats order", "Food & Dining"),
    ("Grubhub delivery", "Food & Dining"),
    ("Postmates food", "Food & Dining"),
    ("Restaurant tip", "Food & Dining"),
    ("Dinner with friends", "Food & Dining"),
    ("Lunch meeting", "Food & Dining"),
    ("Date night dinner", "Food & Dining"),

    # Groceries (50+ examples)
    ("Walmart groceries", "Groceries"),
    ("Target grocery run", "Groceries"),
    ("Costco bulk shopping", "Groceries"),
    ("Kroger supermarket", "Groceries"),
    ("Safeway groceries", "Groceries"),
    ("Whole Foods Market", "Groceries"),
    ("Trader Joe's", "Groceries"),
    ("Aldi grocery store", "Groceries"),
    ("Publix supermarket", "Groceries"),
    ("HEB grocery", "Groceries"),
    ("Wegmans shopping", "Groceries"),
    ("Food Lion", "Groceries"),
    ("Giant Eagle", "Groceries"),
    ("Stop and Shop", "Groceries"),
    ("ShopRite groceries", "Groceries"),
    ("Albertsons", "Groceries"),
    ("Vons supermarket", "Groceries"),
    ("Ralphs grocery", "Groceries"),
    ("Fred Meyer", "Groceries"),
    ("Meijer store", "Groceries"),
    ("Sam's Club groceries", "Groceries"),
    ("BJ's Wholesale", "Groceries"),
    ("Sprouts farmers market", "Groceries"),
    ("Fresh Market", "Groceries"),
    ("Grocery outlet", "Groceries"),
    ("Weekly groceries", "Groceries"),
    ("Milk and eggs", "Groceries"),
    ("Bread and butter", "Groceries"),
    ("Fruits vegetables", "Groceries"),
    ("Meat and poultry", "Groceries"),
    ("Frozen foods", "Groceries"),
    ("Snacks and drinks", "Groceries"),
    ("Household essentials", "Groceries"),
    ("Pantry items", "Groceries"),
    ("Baby food diapers", "Groceries"),
    ("Pet food supplies", "Groceries"),
    ("Organic produce", "Groceries"),
    ("Fresh fish seafood", "Groceries"),
    ("Deli counter", "Groceries"),
    ("Bakery section", "Groceries"),
    ("Instacart delivery", "Groceries"),
    ("Amazon Fresh", "Groceries"),
    ("Grocery pickup", "Groceries"),
    ("Food shopping", "Groceries"),
    ("Supermarket run", "Groceries"),

    # Transportation (50+ examples)
    ("Uber ride", "Transportation"),
    ("Lyft to airport", "Transportation"),
    ("Uber to work", "Transportation"),
    ("Lyft downtown", "Transportation"),
    ("Taxi fare", "Transportation"),
    ("Yellow cab", "Transportation"),
    ("Airport shuttle", "Transportation"),
    ("Gas station Shell", "Transportation"),
    ("Chevron gas", "Transportation"),
    ("Exxon fuel", "Transportation"),
    ("BP gas station", "Transportation"),
    ("Mobil gas", "Transportation"),
    ("76 gas station", "Transportation"),
    ("Costco gas", "Transportation"),
    ("Gasoline fill up", "Transportation"),
    ("Fuel for car", "Transportation"),
    ("Car wash", "Transportation"),
    ("Parking garage", "Transportation"),
    ("Street parking", "Transportation"),
    ("Parking meter", "Transportation"),
    ("Parking lot fee", "Transportation"),
    ("Airport parking", "Transportation"),
    ("Valet parking", "Transportation"),
    ("Toll road", "Transportation"),
    ("Highway toll", "Transportation"),
    ("Bridge toll", "Transportation"),
    ("EZ Pass toll", "Transportation"),
    ("FasTrak toll", "Transportation"),
    ("Metro bus fare", "Transportation"),
    ("Subway ticket", "Transportation"),
    ("Train ticket", "Transportation"),
    ("BART fare", "Transportation"),
    ("Metro card refill", "Transportation"),
    ("Bus pass monthly", "Transportation"),
    ("Transit fare", "Transportation"),
    ("Amtrak train", "Transportation"),
    ("Greyhound bus", "Transportation"),
    ("Car rental Hertz", "Transportation"),
    ("Enterprise rental", "Transportation"),
    ("Avis car rental", "Transportation"),
    ("Budget rental car", "Transportation"),
    ("Turo car rental", "Transportation"),
    ("Zipcar rental", "Transportation"),
    ("Bike share", "Transportation"),
    ("Lime scooter", "Transportation"),
    ("Bird scooter", "Transportation"),
    ("Electric scooter rental", "Transportation"),
    ("Oil change", "Transportation"),
    ("Car maintenance", "Transportation"),
    ("Auto repair shop", "Transportation"),
    ("Tire rotation", "Transportation"),
    ("Brake service", "Transportation"),
    ("Car inspection", "Transportation"),
    ("DMV registration", "Transportation"),
    ("Vehicle registration", "Transportation"),

    # Housing (40+ examples)
    ("Rent payment", "Housing"),
    ("Monthly rent", "Housing"),
    ("Apartment rent", "Housing"),
    ("House payment", "Housing"),
    ("Mortgage payment", "Housing"),
    ("Home loan payment", "Housing"),
    ("HOA fees", "Housing"),
    ("Homeowners association", "Housing"),
    ("Condo fees", "Housing"),
    ("Property tax", "Housing"),
    ("Home insurance", "Housing"),
    ("Renters insurance", "Housing"),
    ("Security deposit", "Housing"),
    ("Home maintenance", "Housing"),
    ("House repair", "Housing"),
    ("Plumber service", "Housing"),
    ("Electrician", "Housing"),
    ("HVAC repair", "Housing"),
    ("Roof repair", "Housing"),
    ("Home improvement", "Housing"),
    ("Furniture purchase", "Housing"),
    ("Home Depot", "Housing"),
    ("Lowes hardware", "Housing"),
    ("Ikea furniture", "Housing"),
    ("Bed Bath Beyond", "Housing"),
    ("Home decor", "Housing"),
    ("Cleaning supplies", "Housing"),
    ("Lawn care", "Housing"),
    ("Landscaping service", "Housing"),
    ("Pest control", "Housing"),
    ("House cleaning service", "Housing"),
    ("Moving expenses", "Housing"),
    ("Storage unit", "Housing"),
    ("Lock change", "Housing"),
    ("Appliance repair", "Housing"),
    ("Washer dryer", "Housing"),
    ("Refrigerator", "Housing"),
    ("Dishwasher", "Housing"),

    # Utilities (40+ examples)
    ("Electric bill", "Utilities"),
    ("PG&E utility", "Utilities"),
    ("Edison electric", "Utilities"),
    ("Power company", "Utilities"),
    ("Electricity payment", "Utilities"),
    ("Gas bill", "Utilities"),
    ("Natural gas", "Utilities"),
    ("Water bill", "Utilities"),
    ("Water utility", "Utilities"),
    ("Sewer bill", "Utilities"),
    ("Trash collection", "Utilities"),
    ("Garbage pickup", "Utilities"),
    ("Waste management", "Utilities"),
    ("Internet bill", "Utilities"),
    ("Comcast Xfinity", "Utilities"),
    ("AT&T internet", "Utilities"),
    ("Verizon Fios", "Utilities"),
    ("Spectrum internet", "Utilities"),
    ("Cox cable", "Utilities"),
    ("WiFi service", "Utilities"),
    ("Phone bill", "Utilities"),
    ("Cell phone bill", "Utilities"),
    ("T-Mobile", "Utilities"),
    ("Verizon wireless", "Utilities"),
    ("AT&T mobile", "Utilities"),
    ("Sprint phone", "Utilities"),
    ("Mobile service", "Utilities"),
    ("Landline phone", "Utilities"),
    ("Cable TV bill", "Utilities"),
    ("TV service", "Utilities"),
    ("Heating oil", "Utilities"),
    ("Propane gas", "Utilities"),
    ("Solar panel", "Utilities"),
    ("Energy bill", "Utilities"),
    ("Utility payment", "Utilities"),

    # Entertainment (40+ examples)
    ("Netflix subscription", "Entertainment"),
    ("Netflix monthly", "Entertainment"),
    ("Hulu streaming", "Entertainment"),
    ("HBO Max", "Entertainment"),
    ("Disney Plus", "Entertainment"),
    ("Amazon Prime Video", "Entertainment"),
    ("Apple TV Plus", "Entertainment"),
    ("Peacock streaming", "Entertainment"),
    ("Paramount Plus", "Entertainment"),
    ("YouTube Premium", "Entertainment"),
    ("Movie tickets", "Entertainment"),
    ("AMC theaters", "Entertainment"),
    ("Regal cinema", "Entertainment"),
    ("Movie night", "Entertainment"),
    ("Concert tickets", "Entertainment"),
    ("Live Nation concert", "Entertainment"),
    ("Ticketmaster", "Entertainment"),
    ("StubHub tickets", "Entertainment"),
    ("Sports game tickets", "Entertainment"),
    ("NBA game", "Entertainment"),
    ("NFL football", "Entertainment"),
    ("MLB baseball", "Entertainment"),
    ("NHL hockey", "Entertainment"),
    ("Theater tickets", "Entertainment"),
    ("Broadway show", "Entertainment"),
    ("Comedy show", "Entertainment"),
    ("Stand up comedy", "Entertainment"),
    ("Amusement park", "Entertainment"),
    ("Disneyland tickets", "Entertainment"),
    ("Six Flags", "Entertainment"),
    ("Universal Studios", "Entertainment"),
    ("Zoo admission", "Entertainment"),
    ("Museum ticket", "Entertainment"),
    ("Aquarium visit", "Entertainment"),
    ("Bowling alley", "Entertainment"),
    ("Mini golf", "Entertainment"),
    ("Arcade games", "Entertainment"),
    ("Video game purchase", "Entertainment"),
    ("PlayStation game", "Entertainment"),
    ("Xbox game", "Entertainment"),
    ("Nintendo Switch", "Entertainment"),
    ("Steam game", "Entertainment"),
    ("Board games", "Entertainment"),

    # Shopping (50+ examples)
    ("Amazon purchase", "Shopping"),
    ("Amazon order", "Shopping"),
    ("Amazon Prime", "Shopping"),
    ("eBay purchase", "Shopping"),
    ("Walmart online", "Shopping"),
    ("Target shopping", "Shopping"),
    ("Best Buy electronics", "Shopping"),
    ("Apple Store", "Shopping"),
    ("Clothing purchase", "Shopping"),
    ("Zara clothes", "Shopping"),
    ("H&M fashion", "Shopping"),
    ("Forever 21", "Shopping"),
    ("Gap clothing", "Shopping"),
    ("Old Navy", "Shopping"),
    ("Banana Republic", "Shopping"),
    ("J Crew", "Shopping"),
    ("Nordstrom", "Shopping"),
    ("Macys department", "Shopping"),
    ("Kohls store", "Shopping"),
    ("JCPenney", "Shopping"),
    ("TJ Maxx", "Shopping"),
    ("Marshalls", "Shopping"),
    ("Ross dress for less", "Shopping"),
    ("Burlington coat", "Shopping"),
    ("Nike shoes", "Shopping"),
    ("Adidas sneakers", "Shopping"),
    ("Foot Locker", "Shopping"),
    ("DSW shoes", "Shopping"),
    ("Sephora makeup", "Shopping"),
    ("Ulta Beauty", "Shopping"),
    ("Bath Body Works", "Shopping"),
    ("Victoria Secret", "Shopping"),
    ("Lululemon", "Shopping"),
    ("REI outdoor", "Shopping"),
    ("Dick's sporting", "Shopping"),
    ("Sports Authority", "Shopping"),
    ("GameStop", "Shopping"),
    ("Books purchase", "Shopping"),
    ("Barnes Noble", "Shopping"),
    ("Etsy handmade", "Shopping"),
    ("Wayfair furniture", "Shopping"),
    ("Overstock", "Shopping"),
    ("Chewy pet supplies", "Shopping"),
    ("PetSmart", "Shopping"),
    ("Petco store", "Shopping"),
    ("Dollar Tree", "Shopping"),
    ("Dollar General", "Shopping"),
    ("Five Below", "Shopping"),
    ("Office Depot", "Shopping"),
    ("Staples office", "Shopping"),

    # Healthcare (40+ examples)
    ("Doctor visit", "Healthcare"),
    ("Doctor appointment", "Healthcare"),
    ("Primary care", "Healthcare"),
    ("Specialist visit", "Healthcare"),
    ("Hospital bill", "Healthcare"),
    ("Emergency room", "Healthcare"),
    ("Urgent care", "Healthcare"),
    ("CVS pharmacy", "Healthcare"),
    ("Walgreens pharmacy", "Healthcare"),
    ("Rite Aid", "Healthcare"),
    ("Prescription medication", "Healthcare"),
    ("Medicine purchase", "Healthcare"),
    ("Dentist appointment", "Healthcare"),
    ("Dental cleaning", "Healthcare"),
    ("Dental work", "Healthcare"),
    ("Orthodontist", "Healthcare"),
    ("Eye doctor", "Healthcare"),
    ("Optometrist visit", "Healthcare"),
    ("Glasses purchase", "Healthcare"),
    ("Contact lenses", "Healthcare"),
    ("Vision care", "Healthcare"),
    ("LensCrafters", "Healthcare"),
    ("Lab work", "Healthcare"),
    ("Blood test", "Healthcare"),
    ("X-ray imaging", "Healthcare"),
    ("MRI scan", "Healthcare"),
    ("Physical therapy", "Healthcare"),
    ("Chiropractor", "Healthcare"),
    ("Mental health", "Healthcare"),
    ("Therapy session", "Healthcare"),
    ("Counseling", "Healthcare"),
    ("Psychiatrist", "Healthcare"),
    ("Health insurance", "Healthcare"),
    ("Medical insurance", "Healthcare"),
    ("Copay payment", "Healthcare"),
    ("Deductible", "Healthcare"),
    ("Vitamin supplements", "Healthcare"),
    ("First aid supplies", "Healthcare"),
    ("Medical supplies", "Healthcare"),

    # Education (35+ examples)
    ("College tuition", "Education"),
    ("University fees", "Education"),
    ("School tuition", "Education"),
    ("Online course", "Education"),
    ("Udemy course", "Education"),
    ("Coursera subscription", "Education"),
    ("LinkedIn Learning", "Education"),
    ("Skillshare", "Education"),
    ("MasterClass", "Education"),
    ("Textbooks purchase", "Education"),
    ("School supplies", "Education"),
    ("College books", "Education"),
    ("Student loan payment", "Education"),
    ("School fees", "Education"),
    ("Registration fees", "Education"),
    ("Exam fees", "Education"),
    ("SAT test", "Education"),
    ("GRE exam", "Education"),
    ("GMAT test", "Education"),
    ("Tutoring service", "Education"),
    ("Private tutor", "Education"),
    ("Music lessons", "Education"),
    ("Piano lessons", "Education"),
    ("Guitar lessons", "Education"),
    ("Art class", "Education"),
    ("Cooking class", "Education"),
    ("Language course", "Education"),
    ("Duolingo Plus", "Education"),
    ("Kids school", "Education"),
    ("Daycare tuition", "Education"),
    ("Preschool fees", "Education"),
    ("After school program", "Education"),
    ("Summer camp", "Education"),
    ("Educational toys", "Education"),
    ("Learning materials", "Education"),

    # Personal Care (35+ examples)
    ("Haircut", "Personal Care"),
    ("Hair salon", "Personal Care"),
    ("Barber shop", "Personal Care"),
    ("Hair styling", "Personal Care"),
    ("Hair coloring", "Personal Care"),
    ("Nail salon", "Personal Care"),
    ("Manicure pedicure", "Personal Care"),
    ("Spa treatment", "Personal Care"),
    ("Massage", "Personal Care"),
    ("Facial treatment", "Personal Care"),
    ("Waxing service", "Personal Care"),
    ("Skincare products", "Personal Care"),
    ("Makeup cosmetics", "Personal Care"),
    ("Toiletries", "Personal Care"),
    ("Shampoo conditioner", "Personal Care"),
    ("Body lotion", "Personal Care"),
    ("Deodorant", "Personal Care"),
    ("Razor blades", "Personal Care"),
    ("Shaving cream", "Personal Care"),
    ("Toothpaste", "Personal Care"),
    ("Dental hygiene", "Personal Care"),
    ("Perfume cologne", "Personal Care"),
    ("Fragrance", "Personal Care"),
    ("Gym membership", "Personal Care"),
    ("Fitness center", "Personal Care"),
    ("Planet Fitness", "Personal Care"),
    ("LA Fitness", "Personal Care"),
    ("24 Hour Fitness", "Personal Care"),
    ("CrossFit gym", "Personal Care"),
    ("Yoga class", "Personal Care"),
    ("Pilates studio", "Personal Care"),
    ("Personal trainer", "Personal Care"),
    ("Weight loss program", "Personal Care"),
    ("Meditation app", "Personal Care"),
    ("Headspace subscription", "Personal Care"),

    # Travel (40+ examples)
    ("Flight ticket", "Travel"),
    ("Airline ticket", "Travel"),
    ("United Airlines", "Travel"),
    ("Delta flight", "Travel"),
    ("American Airlines", "Travel"),
    ("Southwest Airlines", "Travel"),
    ("JetBlue flight", "Travel"),
    ("Spirit Airlines", "Travel"),
    ("Frontier flight", "Travel"),
    ("Alaska Airlines", "Travel"),
    ("International flight", "Travel"),
    ("Hotel booking", "Travel"),
    ("Marriott hotel", "Travel"),
    ("Hilton hotel", "Travel"),
    ("Hyatt hotel", "Travel"),
    ("Holiday Inn", "Travel"),
    ("Best Western", "Travel"),
    ("Airbnb rental", "Travel"),
    ("VRBO vacation", "Travel"),
    ("Booking.com", "Travel"),
    ("Expedia travel", "Travel"),
    ("Hotels.com", "Travel"),
    ("Kayak booking", "Travel"),
    ("Priceline travel", "Travel"),
    ("Vacation package", "Travel"),
    ("Travel insurance", "Travel"),
    ("Passport renewal", "Travel"),
    ("Visa application", "Travel"),
    ("TSA PreCheck", "Travel"),
    ("Global Entry", "Travel"),
    ("Luggage purchase", "Travel"),
    ("Travel accessories", "Travel"),
    ("Cruise booking", "Travel"),
    ("Carnival cruise", "Travel"),
    ("Royal Caribbean", "Travel"),
    ("Resort stay", "Travel"),
    ("Beach vacation", "Travel"),
    ("Ski trip", "Travel"),
    ("Road trip expenses", "Travel"),
    ("Vacation spending", "Travel"),

    # Subscriptions (40+ examples)
    ("Spotify Premium", "Subscriptions"),
    ("Spotify monthly", "Subscriptions"),
    ("Apple Music", "Subscriptions"),
    ("Amazon Music", "Subscriptions"),
    ("Pandora Plus", "Subscriptions"),
    ("Tidal music", "Subscriptions"),
    ("SiriusXM radio", "Subscriptions"),
    ("Audible subscription", "Subscriptions"),
    ("Kindle Unlimited", "Subscriptions"),
    ("Amazon Prime membership", "Subscriptions"),
    ("Costco membership", "Subscriptions"),
    ("Sam's Club membership", "Subscriptions"),
    ("BJ's membership", "Subscriptions"),
    ("AAA membership", "Subscriptions"),
    ("Dropbox Plus", "Subscriptions"),
    ("iCloud storage", "Subscriptions"),
    ("Google One storage", "Subscriptions"),
    ("Microsoft 365", "Subscriptions"),
    ("Adobe Creative Cloud", "Subscriptions"),
    ("Photoshop subscription", "Subscriptions"),
    ("Canva Pro", "Subscriptions"),
    ("Grammarly Premium", "Subscriptions"),
    ("Evernote Premium", "Subscriptions"),
    ("Notion subscription", "Subscriptions"),
    ("Slack subscription", "Subscriptions"),
    ("Zoom subscription", "Subscriptions"),
    ("VPN service", "Subscriptions"),
    ("NordVPN", "Subscriptions"),
    ("ExpressVPN", "Subscriptions"),
    ("Password manager", "Subscriptions"),
    ("1Password", "Subscriptions"),
    ("LastPass", "Subscriptions"),
    ("Antivirus subscription", "Subscriptions"),
    ("Norton antivirus", "Subscriptions"),
    ("McAfee", "Subscriptions"),
    ("News subscription", "Subscriptions"),
    ("New York Times", "Subscriptions"),
    ("Wall Street Journal", "Subscriptions"),
    ("Washington Post", "Subscriptions"),
    ("Magazine subscription", "Subscriptions"),

    # Other (30+ examples)
    ("ATM withdrawal", "Other"),
    ("Cash withdrawal", "Other"),
    ("Bank fee", "Other"),
    ("Wire transfer", "Other"),
    ("Money transfer", "Other"),
    ("Venmo payment", "Other"),
    ("PayPal transfer", "Other"),
    ("Zelle transfer", "Other"),
    ("Cash App", "Other"),
    ("Gift purchase", "Other"),
    ("Birthday gift", "Other"),
    ("Wedding gift", "Other"),
    ("Baby shower gift", "Other"),
    ("Christmas gifts", "Other"),
    ("Holiday gifts", "Other"),
    ("Charity donation", "Other"),
    ("Church donation", "Other"),
    ("Nonprofit donation", "Other"),
    ("GoFundMe contribution", "Other"),
    ("Tips gratuity", "Other"),
    ("Service tip", "Other"),
    ("Late fee", "Other"),
    ("Penalty charge", "Other"),
    ("Interest charge", "Other"),
    ("Miscellaneous expense", "Other"),
    ("Random purchase", "Other"),
    ("Unknown charge", "Other"),
    ("Other expense", "Other"),
    ("General expense", "Other"),
    ("Uncategorized", "Other"),
]

# Category name to default category mapping
CATEGORY_NAMES = [
    "Food & Dining",
    "Groceries",
    "Transportation",
    "Housing",
    "Utilities",
    "Entertainment",
    "Shopping",
    "Healthcare",
    "Education",
    "Personal Care",
    "Travel",
    "Subscriptions",
    "Other",
]


def get_training_descriptions():
    """Return list of expense descriptions."""
    return [item[0] for item in TRAINING_DATA]


def get_training_categories():
    """Return list of corresponding categories."""
    return [item[1] for item in TRAINING_DATA]


def get_category_names():
    """Return list of all category names."""
    return CATEGORY_NAMES
